# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-05 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0002_auto_20170303_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='cities',
            name='country_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
