# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-05 13:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0003_cities_country_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cities',
            options={},
        ),
        migrations.RemoveField(
            model_name='cities',
            name='country_name',
        ),
    ]
