# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-05 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0004_auto_20170305_1310'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stationId', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Cities',
        ),
    ]
